package hotelsoftware.gui.checkin.subpanels;

import hotelsoftware.controller.checkin.CheckInGuiControler;
import hotelsoftware.controller.data.service.ExtraServiceData;
import hotelsoftware.controller.data.service.HabitationData;
import hotelsoftware.controller.data.service.ServiceData;
import java.awt.*;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComponent;

/**
 * Dieses Panel ist dazu da, um die Extraservices graphisch abzubilden.
 *
 * @author Johannes
 */
public class ExtraServicesPanel extends javax.swing.JPanel
{
    /**
     * Creates new form ExtraServicesPanel
     */
    public ExtraServicesPanel()
    {
        initComponents();
        init();
    }
    List<JCheckBox> checkboxes = new LinkedList<JCheckBox>();
    Collection<ExtraServiceData> services = CheckInGuiControler.getInstance().getAllHabitationServices();
    HashMap<String, ExtraServiceData> nameToService = new HashMap<String, ExtraServiceData>();

    private void init()
    {

        this.removeAll();
        this.setLayout(new GridLayout(services.size(), 1));

        for (ExtraServiceData data : services)
        {
            nameToService.put(data.getName(), data);
            JCheckBox checki = new JCheckBox(data.getName());

            checkboxes.add(checki);

            add(checki);
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public Collection<ExtraServiceData> getExtraservices()
    {
        Collection<ExtraServiceData> eServices = new LinkedList<ExtraServiceData>();
        for (JCheckBox c : checkboxes)
        {
            if (c.isSelected())
            {
                eServices.add(nameToService.get(c.getText()));
            }
        }
        return eServices;
    }

    void setExtraservice(ServiceData serviceData)
    {
       for(JCheckBox c : checkboxes)
       {
           if(c.getText().equals(serviceData.getServiceTypeData().getName()))
           {
               c.setSelected(true);
           }
       }
    }
}