/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelsoftware.gui.checkin;

import hotelsoftware.gui.home.HomePanel;
import hotelsoftware.controller.data.room.RoomData;
import hotelsoftware.controller.data.service.HabitationData;
import hotelsoftware.util.weatherservice.CurrentWeather;
import hotelsoftware.util.weatherservice.CurrentWeatherPanel;
import hotelsoftware.util.weatherservice.ForeCastWeatherPanel;
import hotelsoftware.util.weatherservice.Weather;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.Collection;
import java.util.List;
import javax.swing.JLabel;

/**
 * Dieses Panel ist dafür da um nach einem Check-In anzuzeigen, dass alles funktioniert hat
 *
 * @author Johannes
 */
public class SuccesPanel extends javax.swing.JPanel
{
    /**
     * Creates new form SuccesPanel
     */
    public SuccesPanel()
    {
        initComponents();
        jLabel1.setText("<html> <font coloer=#AAFFCC size=+3>Success</font></html>");
        init();
    }

    private void init()
    {
        jPanel1.removeAll();
        JLabel jbl = new JLabel();
        jPanel1.add(jbl);
        displayHabitations(jbl);
        CheckInGuiControler.getInstance().clear();
        repaint();
    }

    /**
     * Zeigt die fertig gebuchten Buchungen auf dem Successpanel
     *
     * @param lbl ein JLabel, auf dem der Text dargestellt wird.
     */
    private void displayHabitations(JLabel lbl)
    {
        Collection<HabitationData> list = CheckInGuiControler.getInstance().getHabitationsData();
        StringBuilder sb = new StringBuilder();
        sb.append("<html>");
        for (HabitationData h : list)
        {
            sb.append(h.toString().replace("\n", "<br/>"));
            sb.append("<br/><br/>");
        }
        sb.append("</html>");
        lbl.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setText("Success");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 581, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
