/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelsoftware.gui.invoice;

import javax.swing.JPanel;

/**
 * 
 * @author Lins Christian (christian.lins87@gmail.com)
 */
public class InvoiceMain extends javax.swing.JPanel
{

    /**
     * Creates new form CheckInMain
     */
    public InvoiceMain()
    {
        initComponents();
    }

    
    public JPanel getContentPanel() {
        return this.contentPanel;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        naviagationPanel = new javax.swing.JPanel();
        deconstructiveNavigation = new javax.swing.JPanel();
        buttonAbort = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        constructiveNavigation = new javax.swing.JPanel();
        buttonSelect = new javax.swing.JButton();
        splitCancel = new javax.swing.JButton();
        splitCancel1 = new javax.swing.JButton();

        statePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Home");
        statePanel.add(jLabel2);

        jLabel1.setText(">");
        statePanel.add(jLabel1);

        jLabel3.setText("Intermediat Invoice");
        statePanel.add(jLabel3);

        contentPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        deconstructiveNavigation.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonAbort.setText("Abort");
        buttonAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbortActionPerformed(evt);
            }
        });
        deconstructiveNavigation.add(buttonAbort);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        deconstructiveNavigation.add(backButton);

        constructiveNavigation.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonSelect.setText("Intermediat Invoice");
        buttonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectActionPerformed(evt);
            }
        });
        constructiveNavigation.add(buttonSelect);

        splitCancel.setText("Split/Cancel");
        splitCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitCancelActionPerformed(evt);
            }
        });
        constructiveNavigation.add(splitCancel);

        splitCancel1.setText("Forward (Choose Customer)");
        splitCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitCancel1ActionPerformed(evt);
            }
        });
        constructiveNavigation.add(splitCancel1);

        javax.swing.GroupLayout naviagationPanelLayout = new javax.swing.GroupLayout(naviagationPanel);
        naviagationPanel.setLayout(naviagationPanelLayout);
        naviagationPanelLayout.setHorizontalGroup(
            naviagationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviagationPanelLayout.createSequentialGroup()
                .addComponent(deconstructiveNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(constructiveNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        naviagationPanelLayout.setVerticalGroup(
            naviagationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviagationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(naviagationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(constructiveNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deconstructiveNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(naviagationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(statePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(naviagationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSelectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonSelectActionPerformed
    {//GEN-HEADEREND:event_buttonSelectActionPerformed
        
    }//GEN-LAST:event_buttonSelectActionPerformed

    private void buttonAbortActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonAbortActionPerformed
    {//GEN-HEADEREND:event_buttonAbortActionPerformed
        //Abort Button
       
    }//GEN-LAST:event_buttonAbortActionPerformed

    private void splitCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_splitCancelActionPerformed
    {//GEN-HEADEREND:event_splitCancelActionPerformed

   }//GEN-LAST:event_splitCancelActionPerformed

    private void splitCancel1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_splitCancel1ActionPerformed
    {//GEN-HEADEREND:event_splitCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_splitCancel1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonAbort;
    private javax.swing.JButton buttonSelect;
    private javax.swing.JPanel constructiveNavigation;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel deconstructiveNavigation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel naviagationPanel;
    private javax.swing.JButton splitCancel;
    private javax.swing.JButton splitCancel1;
    private javax.swing.JPanel statePanel;
    // End of variables declaration//GEN-END:variables
}
