/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelsoftware.gui.invoice.home;

/**
 * 
 * @author Lins Christian (christian.lins87@gmail.com)
 */
public class InvoiceHome extends javax.swing.JPanel
{

    /**
     * Creates new form CheckInMain
     */
    public InvoiceHome()
    {
        initComponents();
    }


    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        invoiceHomeTables = new javax.swing.JPanel();
        availableHabitations = new hotelsoftware.gui.invoice.home.habitations();
        dropSelectButtons = new javax.swing.JPanel();
        chooseAll = new javax.swing.JButton();
        chooseSelection = new javax.swing.JButton();
        dropSelected = new javax.swing.JButton();
        dropAll = new javax.swing.JButton();
        selectedHabitations = new hotelsoftware.gui.invoice.home.habitations();
        searchPanel = new javax.swing.JPanel();
        lnameLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        roomNrLabel = new javax.swing.JLabel();
        fnameTextBox = new javax.swing.JTextField();
        roomNrTextbox = new javax.swing.JTextField();
        lnameTextBox = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        seperator = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1220, 500));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        invoiceHomeTables.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        invoiceHomeTables.add(availableHabitations, gridBagConstraints);

        dropSelectButtons.setMaximumSize(new java.awt.Dimension(32767, 100));
        dropSelectButtons.setPreferredSize(new java.awt.Dimension(80, 240));

        chooseAll.setText("<html><b  style=\"font: 16px\">>></b></html>");
        chooseAll.setToolTipText("Shortcut: Strg+Shift+R");
        chooseAll.setActionCommand("");
        chooseAll.setMaximumSize(new java.awt.Dimension(73, 73));
        chooseAll.setMinimumSize(new java.awt.Dimension(73, 73));
        chooseAll.setPreferredSize(new java.awt.Dimension(80, 80));
        chooseAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseAllActionPerformed(evt);
            }
        });

        chooseSelection.setText("<html><b  style=\"font: 16px\">></b></html>");
        chooseSelection.setToolTipText("Shortcut: Strg+R");
        chooseSelection.setActionCommand("");
        chooseSelection.setMaximumSize(new java.awt.Dimension(73, 73));
        chooseSelection.setMinimumSize(new java.awt.Dimension(73, 73));
        chooseSelection.setPreferredSize(new java.awt.Dimension(80, 80));
        chooseSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseSelectionActionPerformed(evt);
            }
        });

        dropSelected.setText("<html><b  style=\"font: 16px\">&lt;</b></html>");
        dropSelected.setToolTipText("Shortcut: Strg+L");
        dropSelected.setActionCommand("");
        dropSelected.setMaximumSize(new java.awt.Dimension(73, 73));
        dropSelected.setMinimumSize(new java.awt.Dimension(73, 73));
        dropSelected.setPreferredSize(new java.awt.Dimension(80, 80));
        dropSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropSelectedActionPerformed(evt);
            }
        });

        dropAll.setText("<html><b style=\"font: 16px\">&lt;&lt;</b></html>");
        dropAll.setToolTipText("Shortcut: Strg+Shift+L");
        dropAll.setActionCommand("");
        dropAll.setMaximumSize(new java.awt.Dimension(73, 73));
        dropAll.setMinimumSize(new java.awt.Dimension(73, 73));
        dropAll.setPreferredSize(new java.awt.Dimension(80, 80));
        dropAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dropSelectButtonsLayout = new javax.swing.GroupLayout(dropSelectButtons);
        dropSelectButtons.setLayout(dropSelectButtonsLayout);
        dropSelectButtonsLayout.setHorizontalGroup(
            dropSelectButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropSelectButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropSelectButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropAll, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dropSelectButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chooseAll, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dropSelectButtonsLayout.setVerticalGroup(
            dropSelectButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropSelectButtonsLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(chooseAll, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dropSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(dropAll, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        invoiceHomeTables.add(dropSelectButtons, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        invoiceHomeTables.add(selectedHabitations, gridBagConstraints);

        add(invoiceHomeTables, java.awt.BorderLayout.CENTER);

        lnameLabel.setText("Last name:");

        fnameLabel.setText("First name:");

        roomNrLabel.setText("Room Nr");

        fnameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTextBoxActionPerformed(evt);
            }
        });

        roomNrTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNrTextboxActionPerformed(evt);
            }
        });

        lnameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTextBoxActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(lnameLabel)
                                .addGap(35, 35, 35)
                                .addComponent(lnameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(fnameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fnameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addComponent(roomNrLabel)
                        .addGap(35, 35, 35)
                        .addComponent(roomNrTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 841, Short.MAX_VALUE)
                        .addComponent(searchButton))
                    .addComponent(seperator, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(searchButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lnameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roomNrLabel)
                                .addComponent(roomNrTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(fnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(fnameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(seperator, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(searchPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchButtonActionPerformed
    {//GEN-HEADEREND:event_searchButtonActionPerformed
        
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void fnameTextBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fnameTextBoxActionPerformed
    {//GEN-HEADEREND:event_fnameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTextBoxActionPerformed

    private void lnameTextBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lnameTextBoxActionPerformed
    {//GEN-HEADEREND:event_lnameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTextBoxActionPerformed

    private void roomNrTextboxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_roomNrTextboxActionPerformed
    {//GEN-HEADEREND:event_roomNrTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNrTextboxActionPerformed

    private void dropAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dropAllActionPerformed
    {//GEN-HEADEREND:event_dropAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropAllActionPerformed

    private void dropSelectedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dropSelectedActionPerformed
    {//GEN-HEADEREND:event_dropSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropSelectedActionPerformed

    private void chooseSelectionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chooseSelectionActionPerformed
    {//GEN-HEADEREND:event_chooseSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseSelectionActionPerformed

    private void chooseAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chooseAllActionPerformed
    {//GEN-HEADEREND:event_chooseAllActionPerformed
        // TODO add your handling code here:

   }//GEN-LAST:event_chooseAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hotelsoftware.gui.invoice.home.habitations availableHabitations;
    private javax.swing.JButton chooseAll;
    private javax.swing.JButton chooseSelection;
    private javax.swing.JButton dropAll;
    private javax.swing.JPanel dropSelectButtons;
    private javax.swing.JButton dropSelected;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTextBox;
    private javax.swing.JPanel invoiceHomeTables;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTextBox;
    private javax.swing.JLabel roomNrLabel;
    private javax.swing.JTextField roomNrTextbox;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private hotelsoftware.gui.invoice.home.habitations selectedHabitations;
    private javax.swing.JSeparator seperator;
    // End of variables declaration//GEN-END:variables
}
